# Generated by Django 5.1.1 on 2024-10-03 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exploration_donnees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='code_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='confirmation_mot_de_passe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='date_de_naissance',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(1930), django.core.validators.MaxValueValidator(2020)]),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='entreprise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='experience',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='languages',
            field=models.CharField(choices=[('ZA', 'Afrique du Sud'), ('AR', 'Argentine'), ('AU', 'Australie'), ('BE', 'Belgique'), ('BO', 'Bolivie'), ('BR', 'Brésil'), ('CA', 'Canada'), ('KH', 'Cambodge'), ('CL', 'Chili'), ('CN', 'Chine'), ('CO', 'Colombie'), ('EC', 'Équateur'), ('ES', 'Espagne'), ('PH', 'Philippines'), ('FR', 'France'), ('GT', 'Guatemala'), ('IN', 'Inde'), ('ID', 'Indonésie'), ('IE', 'Irlande'), ('IT', 'Italie'), ('JM', 'Jamaïque'), ('JP', 'Japon'), ('MU', 'Maurice'), ('MX', 'Mexique'), ('PY', 'Paraguay'), ('PK', 'Pakistan'), ('PE', 'Pérou'), ('RU', 'Russie'), ('LK', 'Sri Lanka'), ('CH', 'Suisse'), ('TW', 'Taïwan'), ('TN', 'Tunisie'), ('UY', 'Uruguay'), ('VE', 'Venezuela'), ('VN', 'Vietnam')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='mot_de_passe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='pays',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='sexe',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='telephone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
