# Generated by Django 5.1.1 on 2024-10-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exploration_donnees', '0002_utilisateurs_code_postal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Projet', models.CharField(max_length=100)),
                ('csv_file', models.FileField(upload_to='')),
            ],
        ),
    ]
