# Generated by Django 5.1.1 on 2024-10-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exploration_donnees', '0003_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='csv_file',
            field=models.FileField(upload_to='datasets'),
        ),
    ]
