# Generated by Django 5.1.1 on 2024-11-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exploration_donnees', '0005_alter_projet_nom_projet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='csv_file',
            new_name='file',
        ),
    ]
