# Generated by Django 5.1.1 on 2024-09-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoML', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
