name: Django CI

on:
  push:
    branches:
      - kaelig
    paths:
      - "autoML_final/"   # Assure-toi que ce répertoire contient tes fichiers importants
  pull_request:
    branches:
      - kaelig
    paths:
      - "autoML_final/"   # Pareil ici, pour ne suivre que les modifications dans ce dossier

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U ${{ secrets.POSTGRES_USER }}" --health-timeout=30s --health-interval=5s --health-retries=3
      
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASS }}
        options: --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" --health-timeout=30s --health-interval=5s --health-retries=3

    steps:
      # Checkout the code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Choisis la version de Python que tu utilises dans ton projet

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Wait for the Postgres service to be ready
      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U ${{ secrets.POSTGRES_USER }}; do
            echo "Waiting for postgres..."
            sleep 2
          done

      # Wait for MongoDB to be ready
      - name: Wait for MongoDB to be ready
        run: |
          until mongosh --host localhost --port 27017 --username ${{ secrets.MONGO_USER }} --password ${{ secrets.MONGO_PASS }} --eval 'db.adminCommand("ping")'; do
            echo "Waiting for MongoDB..."
            sleep 2
          done

      # Set up Django environment
      - name: Set up Django environment
        run: |
          export DJANGO_SETTINGS_MODULE=autoML_final.settings
          export DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:5432/$POSTGRES_DB
          export MONGO_DB_URI=mongodb://$MONGO_USER:$MONGO_PASS@localhost:27017/$MONGO_DB_NAME

      # Run migrations
      - name: Run migrations
        run: |
          python manage.py migrate

      # Run tests
      - name: Run tests
        run: |
          python manage.py test
