# Generated by Django 5.1.1 on 2025-02-07 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_project',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('projects', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsDatasets',
            fields=[
                ('user_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.user_project')),
                ('datasets', models.JSONField(default=dict)),
            ],
        ),
    ]
