# Generated by Django 5.1.1 on 2025-02-10 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_project',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('projects', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsDatasets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('datasets', models.JSONField(default=dict)),
                ('user_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_project')),
            ],
            options={
                'unique_together': {('user_project', 'project_name')},
            },
        ),
    ]
