# Generated by Django 5.1.1 on 2025-02-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_projectsdatasets_user_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_project',
            name='user',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
